import { beforeEach, describe, expect, it, vi } from 'vitest'

const runMock = vi.fn()
const prepareMock = vi.fn((sql: string) => ({
  run: (...args: any[]) => runMock(sql, ...args),
}))
const getDbMock = vi.fn(() => ({ prepare: prepareMock }))
const isSqliteAvailableMock = vi.fn(() => true)

vi.mock('../../packages/server/src/db/index', () => ({
  getDb: getDbMock,
  isSqliteAvailable: isSqliteAvailableMock,
}))

describe('session title source tracking', () => {
  beforeEach(() => {
    vi.resetModules()
    prepareMock.mockClear()
    runMock.mockReset()
    runMock.mockReturnValue({ changes: 1 })
    getDbMock.mockClear()
    isSqliteAvailableMock.mockReturnValue(true)
  })

  it('marks explicit renames as manual by default', async () => {
    const { renameSession } = await import('../../packages/server/src/db/hermes/session-store')

    expect(renameSession('s1', 'User title')).toBe(true)

    expect(runMock).toHaveBeenCalledWith(
      expect.stringContaining('SET title = ?, title_source = ?'),
      'User title',
      'manual',
      's1',
    )
  })

  it('allows automatic title updates only for non-manual title sources', async () => {
    const { updateAutoGeneratedSessionTitle } = await import('../../packages/server/src/db/hermes/session-store')

    expect(updateAutoGeneratedSessionTitle('s1', ' Compaction title ', 'compaction')).toBe(true)

    expect(runMock).toHaveBeenCalledWith(
      expect.stringContaining("COALESCE(title_source, 'unknown') IN ('initial', 'heuristic', 'compaction', 'llm')"),
      'Compaction title',
      'compaction',
      's1',
    )
    expect(runMock.mock.calls[0][0]).not.toContain("'manual'")
  })

  it('reports skipped automatic title updates when the guarded UPDATE changes no rows', async () => {
    runMock.mockReturnValue({ changes: 0 })
    const { updateAutoGeneratedSessionTitle } = await import('../../packages/server/src/db/hermes/session-store')

    expect(updateAutoGeneratedSessionTitle('s1', 'Ignored title', 'compaction')).toBe(false)
  })
})
