import { beforeEach, describe, expect, it, vi } from 'vitest'

const getSessionMock = vi.fn()
const getSessionDetailMock = vi.fn()
const updateAutoGeneratedSessionTitleMock = vi.fn()
const deleteSessionMock = vi.fn()

vi.mock('../../packages/server/src/db/hermes/session-store', () => ({
  getSession: getSessionMock,
  getSessionDetail: getSessionDetailMock,
  updateAutoGeneratedSessionTitle: updateAutoGeneratedSessionTitleMock,
  deleteSession: deleteSessionMock,
}))

vi.mock('../../packages/server/src/services/logger', () => ({
  logger: {
    warn: vi.fn(),
  },
}))

describe('first-turn session title finalization', () => {
  beforeEach(() => {
    vi.resetModules()
    getSessionMock.mockReset()
    getSessionDetailMock.mockReset()
    updateAutoGeneratedSessionTitleMock.mockReset()
    deleteSessionMock.mockReset()
    updateAutoGeneratedSessionTitleMock.mockReturnValue(true)
  })

  it('replaces the New Chat placeholder with an LLM title after the first assistant response', async () => {
    getSessionMock.mockReturnValue({
      id: 's1',
      profile: 'default',
      title: 'New Chat',
      title_source: 'initial',
      model: 'gpt-test',
      provider: 'test-provider',
    })
    getSessionDetailMock.mockReturnValue({
      id: 's1',
      title: 'New Chat',
      title_source: 'initial',
      messages: [
        { role: 'user', content: 'The title UX is confusing: rename and regenerate overlap.' },
        { role: 'assistant', content: 'Move suggestions into the rename dialog and keep manual confirmation.' },
      ],
    })
    const bridge = {
      request: async (payload: any) => ({
        status: 'completed',
        run_id: 'run-title',
        session_id: payload.session_id,
        output: 'WebUI title UX',
        deltas: [],
        events: [],
      }),
      destroy: async () => undefined,
    }

    const { finalizeFirstTurnSessionTitle } = await import('../../packages/server/src/services/hermes/session-title')
    const result = await finalizeFirstTurnSessionTitle('s1', { bridge })

    expect(result).toEqual({ updated: true, title: 'WebUI title UX', source: 'llm' })
    expect(updateAutoGeneratedSessionTitleMock).toHaveBeenCalledWith('s1', 'WebUI title UX', 'llm')
  })

  it('does not overwrite a manually renamed session', async () => {
    getSessionMock.mockReturnValue({
      id: 's1',
      profile: 'default',
      title: 'User title',
      title_source: 'manual',
      model: 'gpt-test',
      provider: 'test-provider',
    })
    getSessionDetailMock.mockReturnValue({
      id: 's1',
      title: 'User title',
      title_source: 'manual',
      messages: [
        { role: 'user', content: 'The title UX is confusing.' },
        { role: 'assistant', content: 'Use a suggestion inside rename.' },
      ],
    })
    const bridge = {
      request: vi.fn(),
      destroy: async () => undefined,
    }

    const { finalizeFirstTurnSessionTitle } = await import('../../packages/server/src/services/hermes/session-title')
    const result = await finalizeFirstTurnSessionTitle('s1', { bridge })

    expect(result).toEqual({ updated: false })
    expect(bridge.request).not.toHaveBeenCalled()
    expect(updateAutoGeneratedSessionTitleMock).not.toHaveBeenCalled()
  })

  it('only runs during the first user-assistant turn', async () => {
    getSessionMock.mockReturnValue({
      id: 's1',
      profile: 'default',
      title: 'New Chat',
      title_source: 'initial',
      model: 'gpt-test',
      provider: 'test-provider',
    })
    getSessionDetailMock.mockReturnValue({
      id: 's1',
      title: 'New Chat',
      title_source: 'initial',
      messages: [
        { role: 'user', content: 'First question' },
        { role: 'assistant', content: 'First answer' },
        { role: 'user', content: 'Follow-up question' },
      ],
    })
    const bridge = {
      request: vi.fn(),
      destroy: async () => undefined,
    }

    const { finalizeFirstTurnSessionTitle } = await import('../../packages/server/src/services/hermes/session-title')
    const result = await finalizeFirstTurnSessionTitle('s1', { bridge })

    expect(result).toEqual({ updated: false })
    expect(bridge.request).not.toHaveBeenCalled()
    expect(updateAutoGeneratedSessionTitleMock).not.toHaveBeenCalled()
  })

  it('schedules first-turn finalization without blocking completion handlers', async () => {
    getSessionMock.mockReturnValue({
      id: 's1',
      profile: 'default',
      title: 'New Chat',
      title_source: 'initial',
      model: 'gpt-test',
      provider: 'test-provider',
    })
    getSessionDetailMock.mockReturnValue({
      id: 's1',
      title: 'New Chat',
      title_source: 'initial',
      messages: [
        { role: 'user', content: 'Need title UX cleanup.' },
        { role: 'assistant', content: 'Move title suggestions into Rename and preserve manual titles.' },
      ],
    })
    let resolveTitle!: () => void
    const bridge = {
      request: vi.fn(() => new Promise(resolve => {
        resolveTitle = () => resolve({
          status: 'completed',
          run_id: 'run-title',
          output: 'Title UX cleanup',
          deltas: [],
          events: [],
        })
      })),
      destroy: async () => undefined,
    }
    const emit = vi.fn()

    const { scheduleFirstTurnSessionTitleFinalization } = await import('../../packages/server/src/services/hermes/session-title')
    scheduleFirstTurnSessionTitleFinalization('s1', { bridge, emit })

    expect(bridge.request).toHaveBeenCalledTimes(1)
    expect(emit).not.toHaveBeenCalled()

    resolveTitle()
    await new Promise(resolve => setImmediate(resolve))

    expect(updateAutoGeneratedSessionTitleMock).toHaveBeenCalledWith('s1', 'Title UX cleanup', 'llm')
    expect(emit).toHaveBeenCalledWith('session.title.updated', {
      event: 'session.title.updated',
      session_id: 's1',
      title: 'Title UX cleanup',
      titleSource: 'llm',
    })
  })
})
