export function updateProgressHtml(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><style>
:root{color-scheme:light dark;--bg:#f7f8fa;--card:#fff;--text:#20232a;--muted:#687080;--line:#e4e7ed;--accent:#353b47;--error:#b42332}
@media(prefers-color-scheme:dark){:root{--bg:#17191e;--card:#22252d;--text:#f1f3f7;--muted:#a4abba;--line:#363b47;--accent:#c5d3f6;--error:#ff97a2}}
*{box-sizing:border-box}body{margin:0;padding:24px;background:var(--bg);color:var(--text);font:13px system-ui,-apple-system,sans-serif}.header{display:flex;gap:12px;align-items:center;margin-bottom:20px}.icon{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;background:var(--card);border:1px solid var(--line);font-size:23px}h1{font-size:17px;margin:0 0 4px;font-weight:650}.subtitle{color:var(--muted);font-size:12px}.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px}.row{display:flex;justify-content:space-between;align-items:center;gap:12px}#status{font-size:13px}#percent{font-size:21px;font-weight:650;font-variant-numeric:tabular-nums}progress{display:block;appearance:none;width:100%;height:7px;margin:15px 0;border:0;border-radius:8px;overflow:hidden;background:var(--line);accent-color:var(--accent)}progress::-webkit-progress-bar{background:var(--line)}progress::-webkit-progress-value{background:var(--accent);border-radius:8px}body[data-failed="true"] #status{color:var(--error)}body[data-failed="true"] progress::-webkit-progress-value{background:var(--error)}.metrics{color:var(--muted);font-size:11px;font-variant-numeric:tabular-nums}#hint{margin:14px 2px 0;color:var(--muted);line-height:1.6;font-size:11px}
</style></head><body><div class="header"><div class="icon" aria-hidden="true">↓</div><div><h1>Hermes Studio</h1><div id="subtitle" class="subtitle"></div></div></div><div class="card"><div class="row"><span id="status" role="status" aria-live="polite"></span><span id="percent"></span></div><progress id="bar" max="100"></progress><div class="row metrics"><span id="detail"></span><span id="speed"></span></div></div><p id="hint"></p></body></html>`
}
export function normalizeDownloadProgress(value: {percent:number;transferred:number;total:number;bytesPerSecond:number}) {
  const positive=(n:number)=>Number.isFinite(n)?Math.max(0,n):0
  return {percent:Math.min(100,positive(value.percent)),transferred:positive(value.transferred),total:positive(value.total),speed:positive(value.bytesPerSecond)}
}
