import { deleteSession, getSession, getSessionDetail, updateAutoGeneratedSessionTitle } from '../../db/hermes/session-store'
import { logger } from '../logger'
import { AgentBridgeClient, type AgentBridgeRunResult } from './agent-bridge'

export interface SessionTitleMessage {
  role?: string | null
  content?: string | null
}

const TITLE_MAX_LENGTH = 48
export const NEW_CHAT_TITLE = 'New Chat'
const TITLE_MIN_WORD_BOUNDARY = 18
const ENGLISH_STOPWORDS = new Set([
  'a', 'an', 'and', 'are', 'as', 'at', 'be', 'by', 'for', 'from', 'how', 'in', 'into', 'is', 'it', 'of', 'on', 'or', 'over',
  'please', 'propose', 'the', 'this', 'to', 'why', 'with', 'would', 'should', 'could', 'can', 'me', 'we', 'now', 'after',
  'when', 'where', 'what', 'which', 'that', 'there', 'their', 'about', 'does', 'do', 'doing', 'did', 'get', 'give', 'have',
  'has', 'had', 'feel', 'feels', 'feeling', 'looks', 'like', 'really', 'cleaner', 'context', 'menu', 'actions', 'action',
])
const TITLE_KEYWORDS = [
  'webui', 'web ui', 'title', 'rename', 'regenerate', 'compactification', 'compaction', 'ux', 'vite', 'build', 'macos',
  '标题', '重命名', '用户体验', '体验',
]
const TRIVIAL_USER_MESSAGES = new Set([
  'hi',
  'hello',
  'hey',
  'yo',
  'ok',
  'okay',
  'thanks',
  'thank you',
  'test',
  'ping',
])

function containsCjk(text: string): boolean {
  return /[\u3400-\u9FFF\uF900-\uFAFF\u3040-\u30FF\uAC00-\uD7AF]/.test(text)
}

function normalizeLine(line: string): string {
  return line
    .replace(/^\s{0,3}(?:[-*+]\s+|\d+[.)]\s+|#{1,6}\s+|>+\s*)/, '')
    .replace(/^\s*(?:user|assistant|system)\s*:\s*/i, '')
    .trim()
}

function normalizeTitleSource(value: unknown): string {
  if (typeof value !== 'string') return ''

  return value
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`([^`]*)`/g, '$1')
    .replace(/\r/g, '\n')
    .split('\n')
    .map(normalizeLine)
    .filter(Boolean)
    .join(' ')
    .replace(/\s+/g, ' ')
    .replace(/^["'`“”‘’([\{\s]+/, '')
    .replace(/["'`“”‘’)]?[\]}\s]+$/, '')
    .trim()
}

function finalizeTitle(text: string): string {
  const cleaned = text.replace(/[\s,.;:!?。，、；：]+$/g, '').trim()
  if (cleaned.length <= TITLE_MAX_LENGTH) return cleaned

  const slice = cleaned.slice(0, TITLE_MAX_LENGTH - 3)
  const boundary = slice.lastIndexOf(' ')
  const shortened = boundary >= TITLE_MIN_WORD_BOUNDARY ? slice.slice(0, boundary) : slice
  return `${shortened.trim()}...`
}

function titleCaseKeyword(word: string): string {
  const lower = word.toLowerCase()
  if (lower === 'ui') return 'UI'
  if (lower === 'ux') return 'UX'
  if (lower === 'webui') return 'WebUI'
  if (lower === 'macos') return 'macOS'
  if (lower === 'vite') return 'Vite'
  return lower.charAt(0).toUpperCase() + lower.slice(1)
}

function compactEnglishTitle(text: string): string | null {
  const rawWords = text.match(/[A-Za-z][A-Za-z0-9_-]*/g) || []
  if (rawWords.length === 0) return null
  const lowerText = text.toLowerCase()

  if (/\bdebug\b/.test(lowerText) && /\bvite\b/.test(lowerText) && /\bbuild\b/.test(lowerText) && /\bmacos\b/.test(lowerText)) {
    return 'Debug Vite build on macOS'
  }
  if (/\bweb\s*ui\b/.test(lowerText) && /\bsession\b/.test(lowerText) && /\btitle\b/.test(lowerText) && /\bux\b/.test(lowerText)) {
    return 'Web UI session title UX'
  }
  if (/\b(?:compaction|compactification)\b/.test(lowerText) && /\btitle\b/.test(lowerText)) {
    const action = /\binvestigat(?:e|ing|ed|ion)\b/.test(lowerText) ? 'Investigate ' : ''
    return `${action}compaction title behavior`.replace(/\s+/g, ' ').trim()
  }

  const words: string[] = []
  for (const word of rawWords) {
    const lower = word.toLowerCase()
    if (ENGLISH_STOPWORDS.has(lower)) continue
    if (words.some(existing => existing.toLowerCase() === lower)) continue
    words.push(titleCaseKeyword(word))
    if (words.length >= 5) break
  }
  return words.length >= 2 ? words.join(' ') : null
}

function compactTitleCandidate(text: string): string {
  const lower = text.toLowerCase()
  if (text.includes('天气') && /聊|闲聊/.test(text)) {
    return /好|不错|晴|舒服|nice/i.test(text) ? '好天气闲聊' : '天气闲聊'
  }
  if ((lower.includes('webui') || lower.includes('web ui')) &&
    (lower.includes('title') || lower.includes('rename') || text.includes('标题') || text.includes('重命名')) &&
    (lower.includes('ux') || text.includes('用户体验') || text.includes('体验'))) {
    return lower.includes('web ui') ? 'Web UI session title UX' : 'WebUI title UX'
  }
  if (lower.includes('compactification') && (lower.includes('title') || text.includes('标题'))) {
    return 'compactification title'
  }
  if ((lower.includes('compaction') || text.includes('压缩')) && (lower.includes('title') || text.includes('标题'))) {
    return compactEnglishTitle(text) || 'compaction title'
  }
  return compactEnglishTitle(text) || text
}

function isUsefulUserMessage(text: string): boolean {
  if (!text) return false
  if (text.startsWith('/')) return false

  const normalized = text
    .toLowerCase()
    .replace(/["'`“”‘’.,!?。，、:;()[\]{}]/g, '')
    .trim()

  if (!normalized) return false
  if (TRIVIAL_USER_MESSAGES.has(normalized)) return false
  if (containsCjk(text)) return text.length >= 4

  const words = normalized.split(/\s+/).filter(Boolean)
  return text.length >= 12 || words.length >= 3
}

function keywordScore(text: string): number {
  const lower = text.toLowerCase()
  return TITLE_KEYWORDS.reduce((score, keyword) => score + (lower.includes(keyword) || text.includes(keyword) ? 1 : 0), 0)
}

function findTitle(messages: SessionTitleMessage[], role: 'user' | 'assistant', predicate?: (text: string) => boolean): string | null {
  let best: { title: string; score: number; index: number } | null = null
  for (const [index, message] of messages.entries()) {
    if (message.role !== role) continue
    const normalized = normalizeTitleSource(message.content)
    if (!normalized) continue
    if (predicate && !predicate(normalized)) continue
    const compacted = compactTitleCandidate(normalized)
    const title = finalizeTitle(compacted)
    const score = keywordScore(normalized) * 10 + index
    if (!best || score > best.score) best = { title, score, index }
  }
  return best?.title || null
}

export function generateHeuristicSessionTitle(messages: SessionTitleMessage[], fallbackTitle?: string | null): string {
  return (
    findTitle(messages, 'user', isUsefulUserMessage)
    || findTitle(messages, 'assistant')
    || finalizeTitle(normalizeTitleSource(fallbackTitle))
    || 'Untitled session'
  )
}

export function generateInitialSessionTitle(_previewText: string): string {
  return NEW_CHAT_TITLE
}

export type GeneratedSessionTitleSource = 'llm' | 'heuristic'

export interface GenerateLlmSessionTitleOptions {
  messages: SessionTitleMessage[]
  fallbackTitle?: string | null
  profile?: string | null
  model?: string | null
  provider?: string | null
  bridge?: Pick<AgentBridgeClient, 'request' | 'destroy'>
  timeoutMs?: number
}

export interface GeneratedSessionTitle {
  title: string
  source: GeneratedSessionTitleSource
}

function titlePromptMessages(messages: SessionTitleMessage[]): Array<{ role: string; content: string }> {
  const trimmed = messages
    .filter(message => message.role === 'user' || message.role === 'assistant')
    .map(message => ({
      role: message.role === 'assistant' ? 'assistant' : 'user',
      content: normalizeTitleSource(message.content || '').slice(0, 1_200),
    }))
    .filter(message => message.content)

  const firstTurns = trimmed.slice(0, 6)
  const tail = trimmed.length > 6 ? trimmed.slice(-4) : []
  const combined = [...firstTurns]
  for (const item of tail) {
    if (!combined.some(existing => existing.role === item.role && existing.content === item.content)) combined.push(item)
  }
  return combined
}

function cleanGeneratedTitle(raw: string): string {
  const withoutCodeFence = raw
    .replace(/^```(?:\w+)?\s*/i, '')
    .replace(/```$/i, '')
    .trim()
  const line = withoutCodeFence
    .split('\n')
    .map(normalizeLine)
    .find(Boolean) || ''
  const cleaned = line
    .replace(/^\s*(?:title|session title|标题|標題)\s*[:：-]\s*/i, '')
    .replace(/^<[^>]+>|<\/[^>]+>$/g, '')
    .replace(/^["'`“”‘’]+|["'`“”‘’]+$/g, '')
    .trim()
  return finalizeTitle(cleaned)
}

function isGoodGeneratedTitle(title: string): boolean {
  if (!title) return false
  const normalized = title.toLowerCase().trim()
  if (normalized === 'new chat' || normalized === 'untitled' || normalized === 'untitled session') return false
  return title.length >= 2
}

export async function generateLlmSessionTitle(options: GenerateLlmSessionTitleOptions): Promise<string> {
  const timeoutMs = options.timeoutMs ?? 20_000
  const bridge = options.bridge || new AgentBridgeClient({ timeoutMs: timeoutMs + 10_000 })
  const ownsBridge = !options.bridge
  const profile = options.profile || 'default'
  const sessionId = `title_gen_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`
  const history = titlePromptMessages(options.messages)
  const fallback = generateHeuristicSessionTitle(options.messages, options.fallbackTitle || undefined)

  if (history.length === 0) return fallback

  try {
    const result = await bridge.request<AgentBridgeRunResult>({
      action: 'chat',
      session_id: sessionId,
      message: 'Generate the session title now. Return only the title.',
      instructions: [
        'You generate concise chat session titles.',
        `Return exactly one title, max ${TITLE_MAX_LENGTH} characters.`,
        'Capture the actual task or topic, not generic words like chat/session/conversation.',
        'Use the same primary language as the conversation.',
        'No quotes, markdown, trailing punctuation, or explanations.',
      ].join('\n'),
      conversation_history: history,
      profile,
      ...(options.model ? { model: options.model } : {}),
      ...(options.provider ? { provider: options.provider } : {}),
      source: 'internal_title_generation',
      wait: true,
      timeout: Math.ceil(timeoutMs / 1000),
    }, { timeoutMs: timeoutMs + 10_000 })

    if (result.status === 'error') throw new Error(result.error || 'Title bridge run failed')
    const payload = result.result as any
    const title = cleanGeneratedTitle(String(payload?.final_response || result.output || ''))
    if (!isGoodGeneratedTitle(title)) throw new Error('Title bridge run returned an unusable title')
    return title
  } finally {
    await bridge.destroy(sessionId, profile).catch(() => undefined)
    if (ownsBridge) {
      deleteSession(sessionId)
    }
  }
}

export async function generateBestSessionTitle(options: GenerateLlmSessionTitleOptions): Promise<GeneratedSessionTitle> {
  try {
    return {
      title: await generateLlmSessionTitle(options),
      source: 'llm',
    }
  } catch (err) {
    logger.warn({ err: err instanceof Error ? { message: err.message, name: err.name } : err }, 'Session title: LLM title generation failed; falling back to heuristic')
    return {
      title: generateHeuristicSessionTitle(options.messages, options.fallbackTitle || undefined),
      source: 'heuristic',
    }
  }
}

export interface FinalizeFirstTurnTitleOptions {
  bridge?: Pick<AgentBridgeClient, 'request' | 'destroy'>
  profile?: string | null
  model?: string | null
  provider?: string | null
  timeoutMs?: number
}

export type SessionTitleUpdateEmitter = (event: 'session.title.updated', payload: {
  event: 'session.title.updated'
  session_id: string
  title: string
  titleSource: GeneratedSessionTitleSource
}) => void

export interface ScheduleFirstTurnTitleOptions extends FinalizeFirstTurnTitleOptions {
  emit?: SessionTitleUpdateEmitter
}

export interface FinalizeFirstTurnTitleResult {
  updated: boolean
  title?: string
  source?: GeneratedSessionTitleSource
}

function isInitialPlaceholderTitle(title?: string | null, titleSource?: string | null): boolean {
  const normalized = (title || '').trim().toLowerCase()
  return titleSource === 'initial' || normalized === NEW_CHAT_TITLE.toLowerCase()
}

function isFirstUserAssistantTurn(messages: SessionTitleMessage[]): boolean {
  const conversational = messages.filter(message => message.role === 'user' || message.role === 'assistant')
  const users = conversational.filter(message => message.role === 'user')
  const assistants = conversational.filter(message => message.role === 'assistant')
  return conversational.length >= 2 && users.length === 1 && assistants.length >= 1
}

export async function finalizeFirstTurnSessionTitle(
  sessionId: string,
  options: FinalizeFirstTurnTitleOptions = {},
): Promise<FinalizeFirstTurnTitleResult> {
  const session = getSession(sessionId)
  if (!session) return { updated: false }
  if (!isInitialPlaceholderTitle(session.title, session.title_source)) return { updated: false }

  const detail = getSessionDetail(sessionId)
  const messages = detail?.messages || []
  if (!isFirstUserAssistantTurn(messages)) return { updated: false }

  const generated = await generateBestSessionTitle({
    messages,
    fallbackTitle: session.title || undefined,
    profile: options.profile || session.profile,
    model: options.model || session.model,
    provider: options.provider || session.provider,
    bridge: options.bridge,
    timeoutMs: options.timeoutMs,
  })
  const updated = updateAutoGeneratedSessionTitle(sessionId, generated.title, generated.source)
  if (!updated) return { updated: false }
  return { updated: true, title: generated.title, source: generated.source }
}

export function scheduleFirstTurnSessionTitleFinalization(
  sessionId: string,
  options: ScheduleFirstTurnTitleOptions = {},
): void {
  void finalizeFirstTurnSessionTitle(sessionId, options)
    .then(result => {
      if (!result.updated || !result.title || !result.source) return
      options.emit?.('session.title.updated', {
        event: 'session.title.updated',
        session_id: sessionId,
        title: result.title,
        titleSource: result.source,
      })
    })
    .catch(err => {
      logger.warn({
        sessionId,
        err: err instanceof Error ? { message: err.message, name: err.name } : err,
      }, 'Session title: async first-turn finalization failed')
    })
}
